// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgf8bvTTmJxNhXmpsoLkoHONM-GMGWi4k',
    appId: '1:276527746973:web:0de91f9de7d9bd48dfe974',
    messagingSenderId: '276527746973',
    projectId: 'ppua-637e4',
    authDomain: 'ppua-637e4.firebaseapp.com',
    storageBucket: 'ppua-637e4.firebasestorage.app',
    measurementId: 'G-2CYJ7BKT7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbSP0lJyxkCtAD1Bl53rIOAn0nDZ2TzcY',
    appId: '1:276527746973:android:d2e1f1a8b6985176dfe974',
    messagingSenderId: '276527746973',
    projectId: 'ppua-637e4',
    storageBucket: 'ppua-637e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX7TyL4xVLFD2S7uX0i6PNOj8P2I1lNO8',
    appId: '1:276527746973:ios:64cb57eeab273c74dfe974',
    messagingSenderId: '276527746973',
    projectId: 'ppua-637e4',
    storageBucket: 'ppua-637e4.firebasestorage.app',
    iosBundleId: 'com.example.cosmetic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX7TyL4xVLFD2S7uX0i6PNOj8P2I1lNO8',
    appId: '1:276527746973:ios:64cb57eeab273c74dfe974',
    messagingSenderId: '276527746973',
    projectId: 'ppua-637e4',
    storageBucket: 'ppua-637e4.firebasestorage.app',
    iosBundleId: 'com.example.cosmetic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgf8bvTTmJxNhXmpsoLkoHONM-GMGWi4k',
    appId: '1:276527746973:web:72701d220c6f6642dfe974',
    messagingSenderId: '276527746973',
    projectId: 'ppua-637e4',
    authDomain: 'ppua-637e4.firebaseapp.com',
    storageBucket: 'ppua-637e4.firebasestorage.app',
    measurementId: 'G-9W82LJCWTM',
  );
}
